// <auto-generated />
using System;
using ASPNZBat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASPNZBat.Migrations
{
    [DbContext(typeof(SeatBookingDBContext))]
    [Migration("20180910220629_seats")]
    partial class seats
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("ASPNZBat.Models.SeatBooking", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("S1");

                    b.Property<bool>("S10");

                    b.Property<bool>("S11");

                    b.Property<bool>("S12");

                    b.Property<bool>("S13");

                    b.Property<bool>("S14");

                    b.Property<bool>("S15");

                    b.Property<bool>("S16");

                    b.Property<bool>("S2");

                    b.Property<bool>("S3");

                    b.Property<bool>("S4");

                    b.Property<bool>("S5");

                    b.Property<bool>("S6");

                    b.Property<bool>("S7");

                    b.Property<bool>("S8");

                    b.Property<bool>("S9");

                    b.Property<DateTime>("SeatDate");

                    b.Property<string>("StudentIDID");

                    b.HasKey("ID");

                    b.HasIndex("StudentIDID");

                    b.ToTable("SeatBooking");
                });

            modelBuilder.Entity("ASPNZBat.Models.Students", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ASPNZBat.Models.SeatBooking", b =>
                {
                    b.HasOne("ASPNZBat.Models.Students", "StudentID")
                        .WithMany()
                        .HasForeignKey("StudentIDID");
                });
#pragma warning restore 612, 618
        }
    }
}
