// <auto-generated />
using System;
using ASPNZBat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASPNZBat.Migrations
{
    [DbContext(typeof(SeatBookingDBContext))]
    [Migration("20180904221642_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("ASPNZBat.Models.SeatBooking", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("SeatDate");

                    b.Property<string>("StudentIDID");

                    b.HasKey("ID");

                    b.HasIndex("StudentIDID");

                    b.ToTable("SeatBooking");
                });

            modelBuilder.Entity("ASPNZBat.Models.Students", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ASPNZBat.Models.SeatBooking", b =>
                {
                    b.HasOne("ASPNZBat.Models.Students", "StudentID")
                        .WithMany()
                        .HasForeignKey("StudentIDID");
                });
#pragma warning restore 612, 618
        }
    }
}
