// <auto-generated />
using System;
using ASPNZBat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASPNZBat.Migrations
{
    [DbContext(typeof(SeatBookingDBContext))]
    partial class SeatBookingDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("ASPNZBat.Models.AdminData", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("isVisibleS10L");

                    b.Property<bool>("isVisibleS11L");

                    b.Property<bool>("isVisibleS12L");

                    b.Property<bool>("isVisibleS13L");

                    b.Property<bool>("isVisibleS14L");

                    b.Property<bool>("isVisibleS15L");

                    b.Property<bool>("isVisibleS16L");

                    b.Property<bool>("isVisibleS1L");

                    b.Property<bool>("isVisibleS2L");

                    b.Property<bool>("isVisibleS3L");

                    b.Property<bool>("isVisibleS4L");

                    b.Property<bool>("isVisibleS5L");

                    b.Property<bool>("isVisibleS6L");

                    b.Property<bool>("isVisibleS7L");

                    b.Property<bool>("isVisibleS8L");

                    b.Property<bool>("isVisibleS9L");

                    b.HasKey("Id");

                    b.ToTable("AdminData");
                });

            modelBuilder.Entity("ASPNZBat.Models.SeatBooking", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("S1");

                    b.Property<bool>("S10");

                    b.Property<bool>("S11");

                    b.Property<bool>("S12");

                    b.Property<bool>("S13");

                    b.Property<bool>("S14");

                    b.Property<bool>("S15");

                    b.Property<bool>("S2");

                    b.Property<bool>("S3");

                    b.Property<bool>("S4");

                    b.Property<bool>("S5");

                    b.Property<bool>("S6");

                    b.Property<bool>("S7");

                    b.Property<bool>("S8");

                    b.Property<bool>("S9");

                    b.Property<DateTime>("SeatDate");

                    b.Property<DateTime>("SeatDateEnd");

                    b.Property<string>("StudentEmail");

                    b.Property<string>("StudentIDID");

                    b.HasKey("ID");

                    b.HasIndex("StudentIDID");

                    b.ToTable("SeatBooking");
                });

            modelBuilder.Entity("ASPNZBat.Models.Students", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ASPNZBat.Models.SeatBooking", b =>
                {
                    b.HasOne("ASPNZBat.Models.Students", "StudentID")
                        .WithMany()
                        .HasForeignKey("StudentIDID");
                });
#pragma warning restore 612, 618
        }
    }
}
